### ISSUE TITLE
error in go get or go build

### ISSUE THREAD

**Issue by iiaiiappa** [go-oauth2/redis#8]
error in go get or go build
`go get -u -v gopkg.in/go-oauth2/redis.v3`

`# gopkg.in/go-oauth2/redis.v3
..\..\gopath\pkg\mod\gopkg.in\go-oauth2\redis.v3@v3.1.0\options.go:79:3: cannot use o.Dialer (type func(context.Context, string, string) (net.Conn, error)) as type func() (net.Conn, error) in field value
`
Related to this issue #7  error building go-oauth2 redis

Could anyone help fix this?
Thank you very much and have a good day!

**Comment by LyricTian** [comment]
This bug has been fixed before, you can try it again.

**Comment by fr3fou** [comment]
I'm having trouble too! What's up with this?

**Comment by iiaiiappa** [comment]
The bug is still not fixed. Quick fix is:
comment out the line 79:
<your gopath>\pkg\mod\gopkg.in\go-oauth2\redis.v3@v3.1.0\options.go

`//Dialer:             o.Dialer,`

**Comment by fr3fou** [comment]
Should I fork it?
